### ISSUE TITLE
Error when runing speed.py

### ISSUE THREAD

**Issue by weidelongdongqiang** [guyuchao/PyramidCSA#9]
Traceback (most recent call last):
  File "speed.py", line 30, in <module>
    from Models import mobilenetv3temporal_PCSA as net
  File "/media2/program/python/others/video_segment/PyramidCSA-master/Models/mobilenetv3temporal_PCSA.py", line 8, in <module>
    from Models.PCSA import T_Moduel
  File "/media2/program/python/others/video_segment/PyramidCSA-master/Models/PCSA.py", line 2, in <module>
    import self_cuda_backend as _ext
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

How can self_cuda_backend find the right version?

**Comment by guyuchao** [comment]
Need to build it on CUDA10.0.
